filters:
  - BDF_MAG_G_CORRECTED
  - BDF_MAG_R_CORRECTED
  - BDF_MAG_I_CORRECTED
  - BDF_MAG_Z_CORRECTED
  - BDF_MAG_Y_CORRECTED
  - BDF_MAG_W1_CORRECTED
  - BDF_MAG_W2_CORRECTED


filters_err:
  - BDF_MAG_ERR_G
  - BDF_MAG_ERR_R
  - BDF_MAG_ERR_I
  - BDF_MAG_ERR_Z
  - BDF_MAG_ERR_Y
  - BDF_MAG_ERR_W1
  - BDF_MAG_ERR_W2

zspec: Z

bins:
  start: 0.0
  stop: 2.0
  nbins: 100

fit: true
pdf: true
metric: ANF
